corpus_data = [
    ("Alsatian Drama Corpus", "als", "A curated selection of 30 plays written in Alsatian dialect across the 19th and 20th centuries showcasing regional cultural narratives, folk traditions and linguistic particularities."),
    ("American Drama Corpus", "am", "A collection of 40 early American plays from colonial to early 20th-century periods, reflecting the nation’s evolving cultural identity, social issues and theatrical innovations."),
    ("Bashkir Drama Corpus", "bash", "A small yet significant set of three plays in Bashkir language in Bashkir language, preserving local folklore, oral traditions and linguistic heritage with precise TEI markup."),
    ("Calderón Drama Corpus", "cal", "Over 200 Spanish Golden Age dramas by Pedro Calderón de la Barca Pedro Calderón de la Barca, featuring Baroque allegory, complex theological themes and elaborate staging notes."),
    ("Dutch Drama Corpus", "dutch", "180 Dutch-language plays spanning 1539–1786 covering Protestant moralities, Golden Age comedies and civic pageants."),
    ("English Drama Corpus", "eng", "More than 400 English plays from 1550–1700 including Shakespeare’s contemporaries, with detailed publication metadata and links to digital facsimiles for early modern theater study."),
    ("French Drama Corpus", "fre", "A vast TEI-encoded collection of 1,940 plays from classical to modern French theater from classical to modern French theater, based on Fièvre’s Théâtre Classique,including tragedies, comedies and historical dramas."),
    ("German Drama Corpus", "ger", "733 German-language dramas from the 1500s to the 1940s the 1940s, covering Reformation-era morality plays, Enlightenment masterpieces and modernist experiments."),
    ("German Shakespeare Drama Corpus", "gersh", "German translations of Shakespeare’s 37 plays by Schlegel and Tieck reflecting 19th-century reception, editorial variants and translation practices."),
    ("Greek Drama Corpus", "greek", "40 Ancient Greek plays, including tragedies by Aeschylus, Sophocles Aeschylus, Sophocles, Euripides, and comedies by Aristophanes, adapted from Perseus texts and TEI-encoded for classical studies."),
    ("Hungarian Drama Corpus", "hun", "74 Hungarian-language plays from the 16th–20th centuries 37 plays by Schlegel and Tieck, reflecting 19th-century reception, editorial variants and translation practices."),
    ("Italian Drama Corpus", "ita", "139 Italian plays from the Renaissance to the 20th century century, featuring commedia dell’arte, Baroque tragedies and modern dramas."),
    ("Polish Drama Corpus", "pol", "About 50 Polish plays (1772–1939) reflecting social dramas, patriot narratives and folk-inspired theater."),
    ("Roman Drama Corpus", "rom", "36 classical Roman plays—Plautus, Terence comedies and Seneca tragedies Seneca tragedies."),
    ("Russian Drama Corpus", "rus", "Over 200 plays spanning 1740s Enlightenment satires 19th-century realism and early Soviet theater."),
    ("Shakespeare Drama Corpus", "shake", "The complete 37 Shakespeare plays from the Folger Library , capturing Early Modern English nuances, stage directions and character data."),
    ("Spanish Drama Corpus", "span", "25 Spanish plays (1868–1936) ranging from naturalist realism to avant-garde experiments, curated by BETTE."),
    ("Swedish Drama Corpus", "swe", "68 Swedish plays from circa 1880–1900 national romantic pieces and urban social dramas."),
    ("Tatar Drama Corpus", "tat", "Three Tatar-language plays highlighting cultural lore and linguistic features of Tatar theater."),
    ("Ukrainian Drama Corpus", "u", "40 Ukrainian plays from the 19th and early 20th centuries, reflecting nationalist themes, folklore and social change."),
    ("Yiddish Drama Corpus", "yi", "Three Yiddish-language plays from the Hebrew and Yiddish traditions, capturing theatrical culture post-1940."),
]

image_urls = {
    'als': 'https://www.visit.alsace/wp-content/uploads/lei/pictures/229008828-open-air-theater-2-1600x900.jpg',
    'am': 'https://ew.com/thmb/KG0rGH2U8YP8RpD5_Zpxqosdr8E=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/iceman-cometh-play-1-1f23c6e266bb45a6a1054c49169d7205.jpg',
    'bash': 'https://thumbs.dreamstime.com/b/beautiful-female-dancers-miras-song-dance-ensemble-nrepublic-bashkortostan-russia-wearing-national-flamboyant-164118797.jpg',
    'cal': 'https://img.jihoceskedivadlo.cz/fotogalerie1920/1920_gal_148474387220.jpg',
    'dutch': 'https://foyer.de/wp-content/uploads/2023/07/Dutch-National-Opera-Rusalka-2023_c_Claerchen-and-Matthias-Baus-Act2.jpg',
    'eng': 'https://www.york.ac.uk/media/english/images/writingatyork/waysofreading-play720.jpg',
    'fre': 'https://media.tacdn.com/media/attractions-splice-spp-674x446/06/73/23/8f.jpg',
    'ger': 'https://static01.nyt.com/images/2019/05/21/arts/16berlintheater4/91f362783b304c96b083cb6b16e29365-superJumbo.jpg',
    'gersh': 'https://howlround.com/sites/default/files/styles/max_2000_width/public/2022-09/1hamletontheroad_1.jpg?itok=PGz0VmRg',
    'greek': 'https://images.squarespace-cdn.com/content/v1/57125c2c2b8dde54a34b537f/b2657f38-7474-4b8a-b003-bf0683b716c9/5c77ff38fbebf1a1105c3fe1ae0f8fd8.jpg',
    'hun': 'https://www.vigszinhaz.hu/res/imgcache/d__cc20210130017_rb_1000x1000.jpg',
    'ita': 'https://thetheatretimes.com/wp-content/uploads/2018/09/Rigoletto-2-1024x688.jpg',
    'pol': 'https://thetheatretimes.com/wp-content/uploads/2018/03/second-photo-teatr-21-Profile-1000x640.jpg',
    'rom': 'https://d3vjn2zm46gms2.cloudfront.net/blogs/2016/09/27004221/HHP046-1300x938.jpg',
    'rus': 'https://www.qmul.ac.uk/sllf/media/sllf-new/department-of-russian/images-for-the-russian-ws/IMG-20240320-WA0007.jpg',
    'shake': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Gilbert_WShakespeares_Plays.jpg/1200px-Gilbert_WShakespeares_Plays.jpg',
    'span': 'https://thetheatretimes.com/wp-content/uploads/2016/11/ballet-don-quijote-895062_1280-1280x640.jpg',
    'swe': 'https://www.thenewyorkoptimist.net/uploads/6/6/7/3/66739453/meaganpuppet5_orig.jpg',
    'tat': 'https://tatar-congress.org/wp-content/uploads/2024/12/45410b3ff3b7243c53aab0a87ece9974.jpg',
    'u': 'https://www.critical-stages.org/26/wp-content/uploads/sites/27/2022/12/image8-3.jpeg',
    'yi': 'https://static-cdn.toi-media.com/www/uploads/2014/05/מונולוגים-מהקישקע-צילום-תמי-שחם-1024x640.jpg',

}
